name: Feature request
description: Suggest an idea for Caskit
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: You can write in any language.
  - type: textarea
    id: idea
    attributes:
      label: What would you like Caskit to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it useful for you?
      description: Your use case helps to decide what to build first.
